# Generated by Django 3.1.5 on 2021-04-05 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='backend.LibrosProfile')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=100)),
                ('media_type', models.CharField(choices=[('MOVIE', 'Movie'), ('TV', 'TV Show'), ('BOOK', 'Book')], default='MOVIE', max_length=5)),
                ('year', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.media')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.librosprofile')),
            ],
        ),
    ]
